# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('Drug_name', models.CharField(max_length=225)),
                ('Quantity', models.IntegerField(max_length=100)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
