# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20171206_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('Drug_name', models.CharField(max_length=225)),
                ('Quantity', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Drug')),
            ],
        ),
    ]
