# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='drug',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
