# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20171207_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug_name', models.CharField(max_length=225)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
