# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Drug_details',
        ),
    ]
