# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20180111_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug_details',
            new_name='issue',
        ),
    ]
