# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20180111_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issue',
            new_name='issued_Drug',
        ),
    ]
